/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.logViewer;

import java.awt.Component;
import javax.swing.JLabel;

/**
 *
 * @author Cristiano
 */
public class GenericLabelPanel extends javax.swing.JPanel implements LabelFillerConteiner
{

    /**
     * Creates new form TempLabelPanel
     */
    private final String title;
    private final int labelTextFontSize;
    private final int labelTitleFontSize;
    private PanelFiller panelFiller;
    private final LogViewer logViewer;

    public GenericLabelPanel(LogViewer logViewer, int labelTextFontSize, int labelTitleFontSize, String title)
    {
        this.logViewer = logViewer;
        this.labelTextFontSize = labelTextFontSize;
        this.labelTitleFontSize = labelTitleFontSize;
        this.title = title;
        initFiller();
        initComponents();
//        setLayout(new SpringLayout());
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, title, javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14)));
    }

    @Override
    public void addComponent(Component component)
    {
        add(component);
    }

    @Override
    public LogViewer getParentLogViewer()
    {
        return logViewer;
    }

    private void initFiller()
    {
        panelFiller = new PanelFiller(this, labelTextFontSize, labelTitleFontSize);
    }

    public PanelFiller getPanellFiller()
    {
        return panelFiller;
    }

    public String getTitle()
    {
        return title;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FPGA-1", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
